apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./rbac.yaml
- ./habanalabs-feature-discovery.yaml

namespace: default

images:
- name: hfd-image
  newName: artifactory-kfs.habana-labs.com/k8s-infra-docker-dev/github/habanalabs-feature-discovery
  newTag: 1.0.0
